# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #Docker Login
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name:  Dashboard Service Python
        run: docker build ./app -t manpreet94/python-catalogue
        
      - name: Dashboard Service Cassandra
        run: docker build ./cassandra -t manpreet94/cassandra-catalogue
        
      - name: Recommendation Service Python
        run: docker build ./recommendation -t manpreet94/recommendation-python
        
      - name: Login Service Python
        run: docker build ./Login-API/app -t manpreet94/login-python
        
      - name: Nginx server
        run: docker build ./nginx -t manpreet94/nginx-server
        
      # Checking the Build
      - name: Checking if all is going well!
        run: echo All Built, Lets push to Docker Hub!
        
      - name: docker tag
        run: |
          docker tag python-catalogue manpreet94/python-catalogue
          docker tag cassandra-catalogue manpreet94/cassandra-catalogue
          docker tag recommendation-python manpreet94/recommendation-python
          docker tag login-python manpreet94/login-python
          docker tag manpreet94/nginx-server manpreet94/nginx-server
        
      - name: docker push
        run: |
          docker push manpreet94/python-catalogue
          docker push manpreet94/cassandra-catalogue
          docker push manpreet94/recommendation-python
          docker push manpreet94/login-python
          docker push manpreet94/nginx-server

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
